name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: "Cache Setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"

    - name: "Cache References"
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.cache-setup.outputs.path }}
          .targets.mk
        key: refcache-${{ steps.date.outputs.date }}
        restore-keys: |
          refcache-${{ steps.date.outputs.date }}
          refcache-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload

    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v4
      with:
        path: "draft-*-[0-9][0-9].xml"
